In [1]:
# Importing Libraries
import ast
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt  

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
# make datetime string into datetime object
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])
# make string list in column job_skills into panda series (list) object
df["job_skills"] = df["job_skills"].apply(lambda skill_list: ast.literal_eval(skill_list) if pd.notna(skill_list) else None)

In [15]:
job_list = ["Data Analyst", "Data Engineer", "Data Scientist"]

df_UK = df[(df["job_title_short"].isin(job_list)) & (df["job_country"] == "United Kingdom")].copy()

df_UK

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
15,Data Engineer,Data Engineer,"Aberdeen, UK",via LinkedIn,Temp work,False,United Kingdom,2023-10-19 13:37:16,False,False,United Kingdom,NaN,NaN,NaN,Orion Group,"[python, sql, power bi]","{'analyst_tools': ['power bi'], 'programming':..."
74,Data Analyst,Data Entry/Economic Data Analyst,"Worcester, UK",via BeBee,Full-time,False,United Kingdom,2023-11-01 13:11:18,False,False,United Kingdom,NaN,NaN,NaN,ttgTalentSolutions,"[sql, r, python, tableau, power bi]","{'analyst_tools': ['tableau', 'power bi'], 'pr..."
97,Data Analyst,"Systems & Data Analyst - Exploitation, Missing...",United Kingdom,via Totaljobs,Full-time and Contractor,False,United Kingdom,2023-12-04 13:14:01,True,False,United Kingdom,NaN,NaN,NaN,Solihull Metropolitan Borough Council,None,NaN
152,Data Scientist,Data Science Team Lead,Anywhere,via OnlyDataJobs,Full-time,True,United Kingdom,2023-12-23 13:12:16,False,False,United Kingdom,NaN,NaN,NaN,StepStone Group,"[react, docker]","{'libraries': ['react'], 'other': ['docker']}"
162,Data Engineer,Data Engineer,"London, UK",via LinkedIn,Full-time,False,United Kingdom,2023-11-28 13:18:01,True,False,United Kingdom,NaN,NaN,NaN,Zeelo,"[python, postgresql, dynamodb, aws, fastapi, f...","{'cloud': ['aws'], 'databases': ['postgresql',..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785259,Data Engineer,Data Engineer,Anywhere,via LinkedIn,Full-time,True,United Kingdom,2023-01-06 06:34:26,False,False,United Kingdom,NaN,NaN,NaN,hire|py,"[python, sql, javascript, aws, selenium, graph...","{'cloud': ['aws'], 'libraries': ['selenium', '..."
785485,Data Analyst,Data Quality Analyst,Anywhere,via LinkedIn,Full-time,True,United Kingdom,2023-10-04 06:09:44,False,False,United Kingdom,NaN,NaN,NaN,Viatris,"[sql, sql server, excel, powerpoint]","{'analyst_tools': ['excel', 'powerpoint'], 'da..."
785513,Data Scientist,Data Scientist,"Glasgow, UK",via Jobs Trabajo.org,Full-time,False,United Kingdom,2023-01-22 06:21:21,False,False,United Kingdom,NaN,NaN,NaN,ASA Recruitment,"[r, power bi]","{'analyst_tools': ['power bi'], 'programming':..."
785522,Data Engineer,Lead Data Engineer,"London, UK",via Jobs Trabajo.org,Full-time,False,United Kingdom,2023-01-19 06:16:45,True,False,United Kingdom,NaN,NaN,NaN,bionic-services-ltd,"[sql, python, sql server, aws, snowflake, ssis]","{'analyst_tools': ['ssis'], 'cloud': ['aws', '..."
785642,Data Engineer,Submission for the position: Data Engineer Sen...,"England, UK",via BAE Systems - Talentify,Full-time,False,United Kingdom,2023-01-02 06:31:23,True,False,United Kingdom,NaN,NaN,NaN,BAE Systems - UK,"[python, vue, ssis, ssrs, qlik, confluence, jira]","{'analyst_tools': ['ssis', 'ssrs', 'qlik'], 'a..."

In [17]:
df_UK_exploded = df_UK.explode("job_skills")

df_UK_exploded

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
15,Data Engineer,Data Engineer,"Aberdeen, UK",via LinkedIn,Temp work,False,United Kingdom,2023-10-19 13:37:16,False,False,United Kingdom,NaN,NaN,NaN,Orion Group,python,"{'analyst_tools': ['power bi'], 'programming':..."
15,Data Engineer,Data Engineer,"Aberdeen, UK",via LinkedIn,Temp work,False,United Kingdom,2023-10-19 13:37:16,False,False,United Kingdom,NaN,NaN,NaN,Orion Group,sql,"{'analyst_tools': ['power bi'], 'programming':..."
15,Data Engineer,Data Engineer,"Aberdeen, UK",via LinkedIn,Temp work,False,United Kingdom,2023-10-19 13:37:16,False,False,United Kingdom,NaN,NaN,NaN,Orion Group,power bi,"{'analyst_tools': ['power bi'], 'programming':..."
74,Data Analyst,Data Entry/Economic Data Analyst,"Worcester, UK",via BeBee,Full-time,False,United Kingdom,2023-11-01 13:11:18,False,False,United Kingdom,NaN,NaN,NaN,ttgTalentSolutions,sql,"{'analyst_tools': ['tableau', 'power bi'], 'pr..."
74,Data Analyst,Data Entry/Economic Data Analyst,"Worcester, UK",via BeBee,Full-time,False,United Kingdom,2023-11-01 13:11:18,False,False,United Kingdom,NaN,NaN,NaN,ttgTalentSolutions,r,"{'analyst_tools': ['tableau', 'power bi'], 'pr..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785642,Data Engineer,Submission for the position: Data Engineer Sen...,"England, UK",via BAE Systems - Talentify,Full-time,False,United Kingdom,2023-01-02 06:31:23,True,False,United Kingdom,NaN,NaN,NaN,BAE Systems - UK,ssis,"{'analyst_tools': ['ssis', 'ssrs', 'qlik'], 'a..."
785642,Data Engineer,Submission for the position: Data Engineer Sen...,"England, UK",via BAE Systems - Talentify,Full-time,False,United Kingdom,2023-01-02 06:31:23,True,False,United Kingdom,NaN,NaN,NaN,BAE Systems - UK,ssrs,"{'analyst_tools': ['ssis', 'ssrs', 'qlik'], 'a..."
785642,Data Engineer,Submission for the position: Data Engineer Sen...,"England, UK",via BAE Systems - Talentify,Full-time,False,United Kingdom,2023-01-02 06:31:23,True,False,United Kingdom,NaN,NaN,NaN,BAE Systems - UK,qlik,"{'analyst_tools': ['ssis', 'ssrs', 'qlik'], 'a..."
785642,Data Engineer,Submission for the position: Data Engineer Sen...,"England, UK",via BAE Systems - Talentify,Full-time,False,United Kingdom,2023-01-02 06:31:23,True,False,United Kingdom,NaN,NaN,NaN,BAE Systems - UK,confluence,"{'analyst_tools': ['ssis', 'ssrs', 'qlik'], 'a..."
785642,Data Engineer,Submission for the position: Data Engineer Sen...,"England, UK",via BAE Systems - Talentify,Full-time,False,United Kingdom,2023-01-02 06:31:23,True,False,United Kingdom,NaN,NaN,NaN,BAE Systems - UK,jira,"{'analyst_tools': ['ssis', 'ssrs', 'qlik'], 'a..."

In [ ]:
df_UK_exploded.groupby("job_skills")["job_skills"].agg(["count"]).sort_values(by="count", ascending=False).head(5)

df_UK_exploded.groupby("job_skills")["job_skills"].agg(["count"]).sort_values(by="count", ascending=False)

            count
job_skills
sql         15526
python      14909
azure        6788
aws          5731
excel        5470